# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi

pipeline:
  - name: custom_components.vi_tokenizer.VietnameseTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: word
    min_ngram: 1
    max_ngram: 4
    use_shared_vocab: True
    lowercase: True
  - name: custom_components.fasttext_featurizer.FastTextFeaturizer
    cache_dir: custom_components/pre-trained
    file: cc.vi.300.bin
#  - name: custom_components.printer.Printer
#    alias: after fasttext
  - name: DIETClassifier
    entity_recognition: False
    epochs: 300
    constrain_similarities: True
    batch_strategy: balanced
  - name: ResponseSelector
    featurizers: [ CountVectorsFeaturizer ]
    epochs: 100
    constrain_similarities: True
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1
  - name: CRFEntityExtractor
    BILOU_flag: True
    features: [
      [ "low", "title", "upper" ],
      [
          "bias",
          "low",
          "prefix5",
          "prefix2",
          "suffix5",
          "suffix3",
          "suffix2",
          "upper",
          "title",
          "digit",
          "pattern",
      ],
      [ "low", "title", "upper" ],
    ]
    max_iterations: 50
    L1_c: 0.1
    L2_c: 0.1
    featurizers: [ ]
    split_entities_by_comma:
      category: False
      domestic: False
      foreign: False
      province: False
      news_order_st: False
      news-order_nd: False
      news_order_rd: False
  - name: EntitySynonymMapper



# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
   - name: MemoizationPolicy
   - name: RulePolicy
   - name: TEDPolicy
     max_history: 5
     epochs: 100
     constrain_similarities: true
